services:
  firebase-emulators:
    build:
      context: .
      dockerfile: Dockerfile.firebase
    container_name: firebase-emulators
    working_dir: /app
    ports:
      - "9099:9099"   # Auth
      - "8083:8083"   # Firestore (changed to avoid conflict with your app)
      - "9199:9199"   # Storage
      - "4000:4000"   # Emulator UI

  storage-emulator:
    image: fsouza/fake-gcs-server:1.45.2
    command: [ "--scheme=http" ]
    ports:
      - "4443:4443"
    environment:
      - STORAGE_EMULATOR_HOST=localhost:8081