import React from "react";
import styles from "./postList.module.css"
import PostCard from "../postCard/PostCard";
import Post from "@/models/post";

const PostList = async () => {
    try {
        const posts = [new Post("id", "Lorem Ipsum", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ipsum felis, sollicitudin et nisi in, aliquet vestibulum sem. Pellentesque tempor facilisis rutrum. Vestibulum condimentum placerat risus eget consequat. Proin dictum condimentum est a tincidunt. Curabitur dictum mauris in ex rutrum, sit amet facilisis sapien tempus. Vestibulum a euismod magna. Mauris ipsum mauris, consequat sit amet dignissim vitae, consectetur vulputate elit. Sed sagittis ipsum iaculis, convallis metus porta, mollis dui. Quisque semper risus vitae sollicitudin rhoncus. Donec iaculis sollicitudin lorem, vitae sollicitudin dui vestibulum eu.\n" +
            "\n" +
            "Quisque aliquet auctor ipsum tempus aliquet. Morbi faucibus sit amet lectus id dictum. Praesent vel elit quis ante pellentesque varius. Cras luctus fringilla faucibus. Morbi commodo vulputate auctor. Cras consequat dui nec dui rhoncus, eu suscipit augue molestie. Praesent a maximus augue. Fusce finibus lorem sit amet magna efficitur, vel venenatis risus dignissim. Aenean rhoncus vitae quam non ultricies. Praesent dictum nisl non porta varius. Mauris vitae placerat enim. Pellentesque massa leo, sagittis maximus eros non, euismod auctor diam. Vestibulum tristique lacinia orci, quis auctor magna pharetra nec. Sed vitae urna id tortor ultricies vulputate vel volutpat erat.\n" +
            "\n" +
            "Suspendisse potenti. Aenean sed lobortis odio, vitae volutpat urna. Phasellus at turpis interdum, rutrum libero non, mattis ligula. Pellentesque imperdiet, elit vitae fermentum iaculis, sapien lacus ullamcorper velit, et sagittis nisi quam a turpis. Nullam ac turpis turpis. Fusce at magna eget est euismod aliquet. Vestibulum a pellentesque magna.\n" +
            "\n" +
            "Pellentesque aliquet sodales pretium. Mauris faucibus imperdiet turpis eu eleifend. Phasellus tincidunt ipsum nulla, eu eleifend nisl tempus tempor. Aenean dapibus dui velit. Aenean mattis elit et dolor ullamcorper rhoncus. Nam eu fringilla elit. Nunc ultricies semper lorem, in sollicitudin libero tincidunt sit amet. Mauris luctus vehicula dui, eu suscipit diam molestie in. Phasellus et enim eu leo posuere malesuada. Donec leo odio, semper nec urna ut, fermentum pretium est. Nullam ut felis dolor. Mauris eu quam hendrerit, scelerisque erat ut, commodo sem. Praesent vestibulum velit nec imperdiet scelerisque. Mauris gravida efficitur nulla non elementum. Integer sodales lectus egestas nunc lobortis, eget faucibus augue semper.\n" +
            "\n" +
            "Nunc id tristique orci. Aliquam iaculis tellus non purus dictum congue. Maecenas fringilla non nulla et molestie. Fusce massa dui, tincidunt sed dui eu, laoreet elementum nibh. Nunc efficitur augue in quam tristique, a elementum nibh vestibulum. Maecenas ullamcorper magna tortor, non facilisis est tempor sit amet. Duis dapibus odio in bibendum facilisis.", "2025-01-01", "lorem-ipsum"),

            new Post("id", "Lorem Ipsum", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ipsum felis, sollicitudin et nisi in, aliquet vestibulum sem. Pellentesque tempor facilisis rutrum. Vestibulum condimentum placerat risus eget consequat. Proin dictum condimentum est a tincidunt. Curabitur dictum mauris in ex rutrum, sit amet facilisis sapien tempus. Vestibulum a euismod magna. Mauris ipsum mauris, consequat sit amet dignissim vitae, consectetur vulputate elit. Sed sagittis ipsum iaculis, convallis metus porta, mollis dui. Quisque semper risus vitae sollicitudin rhoncus. Donec iaculis sollicitudin lorem, vitae sollicitudin dui vestibulum eu.\n" +
                "\n" +
                "Quisque aliquet auctor ipsum tempus aliquet. Morbi faucibus sit amet lectus id dictum. Praesent vel elit quis ante pellentesque varius. Cras luctus fringilla faucibus. Morbi commodo vulputate auctor. Cras consequat dui nec dui rhoncus, eu suscipit augue molestie. Praesent a maximus augue. Fusce finibus lorem sit amet magna efficitur, vel venenatis risus dignissim. Aenean rhoncus vitae quam non ultricies. Praesent dictum nisl non porta varius. Mauris vitae placerat enim. Pellentesque massa leo, sagittis maximus eros non, euismod auctor diam. Vestibulum tristique lacinia orci, quis auctor magna pharetra nec. Sed vitae urna id tortor ultricies vulputate vel volutpat erat.\n" +
                "\n" +
                "Suspendisse potenti. Aenean sed lobortis odio, vitae volutpat urna. Phasellus at turpis interdum, rutrum libero non, mattis ligula. Pellentesque imperdiet, elit vitae fermentum iaculis, sapien lacus ullamcorper velit, et sagittis nisi quam a turpis. Nullam ac turpis turpis. Fusce at magna eget est euismod aliquet. Vestibulum a pellentesque magna.\n" +
                "\n" +
                "Pellentesque aliquet sodales pretium. Mauris faucibus imperdiet turpis eu eleifend. Phasellus tincidunt ipsum nulla, eu eleifend nisl tempus tempor. Aenean dapibus dui velit. Aenean mattis elit et dolor ullamcorper rhoncus. Nam eu fringilla elit. Nunc ultricies semper lorem, in sollicitudin libero tincidunt sit amet. Mauris luctus vehicula dui, eu suscipit diam molestie in. Phasellus et enim eu leo posuere malesuada. Donec leo odio, semper nec urna ut, fermentum pretium est. Nullam ut felis dolor. Mauris eu quam hendrerit, scelerisque erat ut, commodo sem. Praesent vestibulum velit nec imperdiet scelerisque. Mauris gravida efficitur nulla non elementum. Integer sodales lectus egestas nunc lobortis, eget faucibus augue semper.\n" +
                "\n" +
                "Nunc id tristique orci. Aliquam iaculis tellus non purus dictum congue. Maecenas fringilla non nulla et molestie. Fusce massa dui, tincidunt sed dui eu, laoreet elementum nibh. Nunc efficitur augue in quam tristique, a elementum nibh vestibulum. Maecenas ullamcorper magna tortor, non facilisis est tempor sit amet. Duis dapibus odio in bibendum facilisis.", "2025-01-01", "lorem-ipsum3"),

            new Post("id", "Lorem Ipsum", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ipsum felis, sollicitudin et nisi in, aliquet vestibulum sem. Pellentesque tempor facilisis rutrum. Vestibulum condimentum placerat risus eget consequat. Proin dictum condimentum est a tincidunt. Curabitur dictum mauris in ex rutrum, sit amet facilisis sapien tempus. Vestibulum a euismod magna. Mauris ipsum mauris, consequat sit amet dignissim vitae, consectetur vulputate elit. Sed sagittis ipsum iaculis, convallis metus porta, mollis dui. Quisque semper risus vitae sollicitudin rhoncus. Donec iaculis sollicitudin lorem, vitae sollicitudin dui vestibulum eu.\n" +
                "\n" +
                "Quisque aliquet auctor ipsum tempus aliquet. Morbi faucibus sit amet lectus id dictum. Praesent vel elit quis ante pellentesque varius. Cras luctus fringilla faucibus. Morbi commodo vulputate auctor. Cras consequat dui nec dui rhoncus, eu suscipit augue molestie. Praesent a maximus augue. Fusce finibus lorem sit amet magna efficitur, vel venenatis risus dignissim. Aenean rhoncus vitae quam non ultricies. Praesent dictum nisl non porta varius. Mauris vitae placerat enim. Pellentesque massa leo, sagittis maximus eros non, euismod auctor diam. Vestibulum tristique lacinia orci, quis auctor magna pharetra nec. Sed vitae urna id tortor ultricies vulputate vel volutpat erat.\n" +
                "\n" +
                "Suspendisse potenti. Aenean sed lobortis odio, vitae volutpat urna. Phasellus at turpis interdum, rutrum libero non, mattis ligula. Pellentesque imperdiet, elit vitae fermentum iaculis, sapien lacus ullamcorper velit, et sagittis nisi quam a turpis. Nullam ac turpis turpis. Fusce at magna eget est euismod aliquet. Vestibulum a pellentesque magna.\n" +
                "\n" +
                "Pellentesque aliquet sodales pretium. Mauris faucibus imperdiet turpis eu eleifend. Phasellus tincidunt ipsum nulla, eu eleifend nisl tempus tempor. Aenean dapibus dui velit. Aenean mattis elit et dolor ullamcorper rhoncus. Nam eu fringilla elit. Nunc ultricies semper lorem, in sollicitudin libero tincidunt sit amet. Mauris luctus vehicula dui, eu suscipit diam molestie in. Phasellus et enim eu leo posuere malesuada. Donec leo odio, semper nec urna ut, fermentum pretium est. Nullam ut felis dolor. Mauris eu quam hendrerit, scelerisque erat ut, commodo sem. Praesent vestibulum velit nec imperdiet scelerisque. Mauris gravida efficitur nulla non elementum. Integer sodales lectus egestas nunc lobortis, eget faucibus augue semper.\n" +
                "\n" +
                "Nunc id tristique orci. Aliquam iaculis tellus non purus dictum congue. Maecenas fringilla non nulla et molestie. Fusce massa dui, tincidunt sed dui eu, laoreet elementum nibh. Nunc efficitur augue in quam tristique, a elementum nibh vestibulum. Maecenas ullamcorper magna tortor, non facilisis est tempor sit amet. Duis dapibus odio in bibendum facilisis.", "2025-01-01", "lorem-ipsum2"),

            new Post("id", "Lorem Ipsum", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ipsum felis, sollicitudin et nisi in, aliquet vestibulum sem. Pellentesque tempor facilisis rutrum. Vestibulum condimentum placerat risus eget consequat. Proin dictum condimentum est a tincidunt. Curabitur dictum mauris in ex rutrum, sit amet facilisis sapien tempus. Vestibulum a euismod magna. Mauris ipsum mauris, consequat sit amet dignissim vitae, consectetur vulputate elit. Sed sagittis ipsum iaculis, convallis metus porta, mollis dui. Quisque semper risus vitae sollicitudin rhoncus. Donec iaculis sollicitudin lorem, vitae sollicitudin dui vestibulum eu.\n" +
                "\n" +
                "Quisque aliquet auctor ipsum tempus aliquet. Morbi faucibus sit amet lectus id dictum. Praesent vel elit quis ante pellentesque varius. Cras luctus fringilla faucibus. Morbi commodo vulputate auctor. Cras consequat dui nec dui rhoncus, eu suscipit augue molestie. Praesent a maximus augue. Fusce finibus lorem sit amet magna efficitur, vel venenatis risus dignissim. Aenean rhoncus vitae quam non ultricies. Praesent dictum nisl non porta varius. Mauris vitae placerat enim. Pellentesque massa leo, sagittis maximus eros non, euismod auctor diam. Vestibulum tristique lacinia orci, quis auctor magna pharetra nec. Sed vitae urna id tortor ultricies vulputate vel volutpat erat.\n" +
                "\n" +
                "Suspendisse potenti. Aenean sed lobortis odio, vitae volutpat urna. Phasellus at turpis interdum, rutrum libero non, mattis ligula. Pellentesque imperdiet, elit vitae fermentum iaculis, sapien lacus ullamcorper velit, et sagittis nisi quam a turpis. Nullam ac turpis turpis. Fusce at magna eget est euismod aliquet. Vestibulum a pellentesque magna.\n" +
                "\n" +
                "Pellentesque aliquet sodales pretium. Mauris faucibus imperdiet turpis eu eleifend. Phasellus tincidunt ipsum nulla, eu eleifend nisl tempus tempor. Aenean dapibus dui velit. Aenean mattis elit et dolor ullamcorper rhoncus. Nam eu fringilla elit. Nunc ultricies semper lorem, in sollicitudin libero tincidunt sit amet. Mauris luctus vehicula dui, eu suscipit diam molestie in. Phasellus et enim eu leo posuere malesuada. Donec leo odio, semper nec urna ut, fermentum pretium est. Nullam ut felis dolor. Mauris eu quam hendrerit, scelerisque erat ut, commodo sem. Praesent vestibulum velit nec imperdiet scelerisque. Mauris gravida efficitur nulla non elementum. Integer sodales lectus egestas nunc lobortis, eget faucibus augue semper.\n" +
                "\n" +
                "Nunc id tristique orci. Aliquam iaculis tellus non purus dictum congue. Maecenas fringilla non nulla et molestie. Fusce massa dui, tincidunt sed dui eu, laoreet elementum nibh. Nunc efficitur augue in quam tristique, a elementum nibh vestibulum. Maecenas ullamcorper magna tortor, non facilisis est tempor sit amet. Duis dapibus odio in bibendum facilisis.", "2025-01-01", "lorem-ipsum3"),

            new Post("id", "Lorem Ipsum", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ipsum felis, sollicitudin et nisi in, aliquet vestibulum sem. Pellentesque tempor facilisis rutrum. Vestibulum condimentum placerat risus eget consequat. Proin dictum condimentum est a tincidunt. Curabitur dictum mauris in ex rutrum, sit amet facilisis sapien tempus. Vestibulum a euismod magna. Mauris ipsum mauris, consequat sit amet dignissim vitae, consectetur vulputate elit. Sed sagittis ipsum iaculis, convallis metus porta, mollis dui. Quisque semper risus vitae sollicitudin rhoncus. Donec iaculis sollicitudin lorem, vitae sollicitudin dui vestibulum eu.\n" +
                "\n" +
                "Quisque aliquet auctor ipsum tempus aliquet. Morbi faucibus sit amet lectus id dictum. Praesent vel elit quis ante pellentesque varius. Cras luctus fringilla faucibus. Morbi commodo vulputate auctor. Cras consequat dui nec dui rhoncus, eu suscipit augue molestie. Praesent a maximus augue. Fusce finibus lorem sit amet magna efficitur, vel venenatis risus dignissim. Aenean rhoncus vitae quam non ultricies. Praesent dictum nisl non porta varius. Mauris vitae placerat enim. Pellentesque massa leo, sagittis maximus eros non, euismod auctor diam. Vestibulum tristique lacinia orci, quis auctor magna pharetra nec. Sed vitae urna id tortor ultricies vulputate vel volutpat erat.\n" +
                "\n" +
                "Suspendisse potenti. Aenean sed lobortis odio, vitae volutpat urna. Phasellus at turpis interdum, rutrum libero non, mattis ligula. Pellentesque imperdiet, elit vitae fermentum iaculis, sapien lacus ullamcorper velit, et sagittis nisi quam a turpis. Nullam ac turpis turpis. Fusce at magna eget est euismod aliquet. Vestibulum a pellentesque magna.\n" +
                "\n" +
                "Pellentesque aliquet sodales pretium. Mauris faucibus imperdiet turpis eu eleifend. Phasellus tincidunt ipsum nulla, eu eleifend nisl tempus tempor. Aenean dapibus dui velit. Aenean mattis elit et dolor ullamcorper rhoncus. Nam eu fringilla elit. Nunc ultricies semper lorem, in sollicitudin libero tincidunt sit amet. Mauris luctus vehicula dui, eu suscipit diam molestie in. Phasellus et enim eu leo posuere malesuada. Donec leo odio, semper nec urna ut, fermentum pretium est. Nullam ut felis dolor. Mauris eu quam hendrerit, scelerisque erat ut, commodo sem. Praesent vestibulum velit nec imperdiet scelerisque. Mauris gravida efficitur nulla non elementum. Integer sodales lectus egestas nunc lobortis, eget faucibus augue semper.\n" +
                "\n" +
                "Nunc id tristique orci. Aliquam iaculis tellus non purus dictum congue. Maecenas fringilla non nulla et molestie. Fusce massa dui, tincidunt sed dui eu, laoreet elementum nibh. Nunc efficitur augue in quam tristique, a elementum nibh vestibulum. Maecenas ullamcorper magna tortor, non facilisis est tempor sit amet. Duis dapibus odio in bibendum facilisis.", "2025-01-01", "lorem-ipsum4"),

            new Post("id", "Lorem Ipsum", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ipsum felis, sollicitudin et nisi in, aliquet vestibulum sem. Pellentesque tempor facilisis rutrum. Vestibulum condimentum placerat risus eget consequat. Proin dictum condimentum est a tincidunt. Curabitur dictum mauris in ex rutrum, sit amet facilisis sapien tempus. Vestibulum a euismod magna. Mauris ipsum mauris, consequat sit amet dignissim vitae, consectetur vulputate elit. Sed sagittis ipsum iaculis, convallis metus porta, mollis dui. Quisque semper risus vitae sollicitudin rhoncus. Donec iaculis sollicitudin lorem, vitae sollicitudin dui vestibulum eu.\n" +
                "\n" +
                "Quisque aliquet auctor ipsum tempus aliquet. Morbi faucibus sit amet lectus id dictum. Praesent vel elit quis ante pellentesque varius. Cras luctus fringilla faucibus. Morbi commodo vulputate auctor. Cras consequat dui nec dui rhoncus, eu suscipit augue molestie. Praesent a maximus augue. Fusce finibus lorem sit amet magna efficitur, vel venenatis risus dignissim. Aenean rhoncus vitae quam non ultricies. Praesent dictum nisl non porta varius. Mauris vitae placerat enim. Pellentesque massa leo, sagittis maximus eros non, euismod auctor diam. Vestibulum tristique lacinia orci, quis auctor magna pharetra nec. Sed vitae urna id tortor ultricies vulputate vel volutpat erat.\n" +
                "\n" +
                "Suspendisse potenti. Aenean sed lobortis odio, vitae volutpat urna. Phasellus at turpis interdum, rutrum libero non, mattis ligula. Pellentesque imperdiet, elit vitae fermentum iaculis, sapien lacus ullamcorper velit, et sagittis nisi quam a turpis. Nullam ac turpis turpis. Fusce at magna eget est euismod aliquet. Vestibulum a pellentesque magna.\n" +
                "\n" +
                "Pellentesque aliquet sodales pretium. Mauris faucibus imperdiet turpis eu eleifend. Phasellus tincidunt ipsum nulla, eu eleifend nisl tempus tempor. Aenean dapibus dui velit. Aenean mattis elit et dolor ullamcorper rhoncus. Nam eu fringilla elit. Nunc ultricies semper lorem, in sollicitudin libero tincidunt sit amet. Mauris luctus vehicula dui, eu suscipit diam molestie in. Phasellus et enim eu leo posuere malesuada. Donec leo odio, semper nec urna ut, fermentum pretium est. Nullam ut felis dolor. Mauris eu quam hendrerit, scelerisque erat ut, commodo sem. Praesent vestibulum velit nec imperdiet scelerisque. Mauris gravida efficitur nulla non elementum. Integer sodales lectus egestas nunc lobortis, eget faucibus augue semper.\n" +
                "\n" +
                "Nunc id tristique orci. Aliquam iaculis tellus non purus dictum congue. Maecenas fringilla non nulla et molestie. Fusce massa dui, tincidunt sed dui eu, laoreet elementum nibh. Nunc efficitur augue in quam tristique, a elementum nibh vestibulum. Maecenas ullamcorper magna tortor, non facilisis est tempor sit amet. Duis dapibus odio in bibendum facilisis.", "2025-01-01", "lorem-ipsum5"),

            new Post("id", "Lorem Ipsum", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ipsum felis, sollicitudin et nisi in, aliquet vestibulum sem. Pellentesque tempor facilisis rutrum. Vestibulum condimentum placerat risus eget consequat. Proin dictum condimentum est a tincidunt. Curabitur dictum mauris in ex rutrum, sit amet facilisis sapien tempus. Vestibulum a euismod magna. Mauris ipsum mauris, consequat sit amet dignissim vitae, consectetur vulputate elit. Sed sagittis ipsum iaculis, convallis metus porta, mollis dui. Quisque semper risus vitae sollicitudin rhoncus. Donec iaculis sollicitudin lorem, vitae sollicitudin dui vestibulum eu.\n" +
                "\n" +
                "Quisque aliquet auctor ipsum tempus aliquet. Morbi faucibus sit amet lectus id dictum. Praesent vel elit quis ante pellentesque varius. Cras luctus fringilla faucibus. Morbi commodo vulputate auctor. Cras consequat dui nec dui rhoncus, eu suscipit augue molestie. Praesent a maximus augue. Fusce finibus lorem sit amet magna efficitur, vel venenatis risus dignissim. Aenean rhoncus vitae quam non ultricies. Praesent dictum nisl non porta varius. Mauris vitae placerat enim. Pellentesque massa leo, sagittis maximus eros non, euismod auctor diam. Vestibulum tristique lacinia orci, quis auctor magna pharetra nec. Sed vitae urna id tortor ultricies vulputate vel volutpat erat.\n" +
                "\n" +
                "Suspendisse potenti. Aenean sed lobortis odio, vitae volutpat urna. Phasellus at turpis interdum, rutrum libero non, mattis ligula. Pellentesque imperdiet, elit vitae fermentum iaculis, sapien lacus ullamcorper velit, et sagittis nisi quam a turpis. Nullam ac turpis turpis. Fusce at magna eget est euismod aliquet. Vestibulum a pellentesque magna.\n" +
                "\n" +
                "Pellentesque aliquet sodales pretium. Mauris faucibus imperdiet turpis eu eleifend. Phasellus tincidunt ipsum nulla, eu eleifend nisl tempus tempor. Aenean dapibus dui velit. Aenean mattis elit et dolor ullamcorper rhoncus. Nam eu fringilla elit. Nunc ultricies semper lorem, in sollicitudin libero tincidunt sit amet. Mauris luctus vehicula dui, eu suscipit diam molestie in. Phasellus et enim eu leo posuere malesuada. Donec leo odio, semper nec urna ut, fermentum pretium est. Nullam ut felis dolor. Mauris eu quam hendrerit, scelerisque erat ut, commodo sem. Praesent vestibulum velit nec imperdiet scelerisque. Mauris gravida efficitur nulla non elementum. Integer sodales lectus egestas nunc lobortis, eget faucibus augue semper.\n" +
                "\n" +
                "Nunc id tristique orci. Aliquam iaculis tellus non purus dictum congue. Maecenas fringilla non nulla et molestie. Fusce massa dui, tincidunt sed dui eu, laoreet elementum nibh. Nunc efficitur augue in quam tristique, a elementum nibh vestibulum. Maecenas ullamcorper magna tortor, non facilisis est tempor sit amet. Duis dapibus odio in bibendum facilisis.", "2025-01-01", "lorem-ipsum6")]
        return (
            <div className={styles.container}>
                {
                    posts.length > 6 && (
                        <div className={styles.headerContainer}>
                            <div className={styles.headerText}>Recent Stories</div>
                            <button className={styles.button}>See more</button>
                        </div>
                    )
                }
                <div className={styles.grid}>
                    {posts.slice(0, 6).map((post) => (
                        <div key={post.postId}>
                            <PostCard {...post} />
                        </div>
                    ))}

                </div>

            </div>
        )
    } catch {
        return <></>
    }

}

export default PostList;
