name: Build

on:
  pull_request:
    paths:
      - '**/blog-backend/**'
      - '**/blog-web/**'

jobs:
  trigger-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Frontend Build
        run: gh workflow run build-frontend.yml

  trigger-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Backend Build
        run: gh workflow run build-backend.yml