name: Build Project

on:
  pull_request:
    paths:
      - '**/blog-backend/**'


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./blog-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Gradle build
        run: ./gradlew build --no-daemon

      - name: Archive Checkstyle and Jacoco reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            ./blog-backend/build/reports
            ./blog-backend/build/jacocoHtml
