name: Deploy to Cloud Run (Gradle)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v4

      - name: Build native Quarkus app with Gradle
        run: ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true

      - name: Build and deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ secrets.SERVICE_NAME }}'
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}
          region: europe-central2
          platform: managed
          allow-unauthenticated: true
